package com.dbapp.mybatis.pojo;

import java.io.Serializable;
import java.util.Date;
import org.apache.ibatis.type.Alias;

/**
 * 实体类 - 表：t_token
 * @since 2017-10-27 17:14:48
 */
@Alias("Token")
public class Token implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.id
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.user_id
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.access_token
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.secret
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.created_time
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.expires_time
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private Date expiresTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.client_ip
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private String clientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.client_type
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.e_code
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private String eCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_token.u_code
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private String uCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_token
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.id
     *
     * @return the value of t_token.id
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.id
     *
     * @param id the value for t_token.id
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.user_id
     *
     * @return the value of t_token.user_id
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.user_id
     *
     * @param userId the value for t_token.user_id
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.access_token
     *
     * @return the value of t_token.access_token
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.access_token
     *
     * @param accessToken the value for t_token.access_token
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.secret
     *
     * @return the value of t_token.secret
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.secret
     *
     * @param secret the value for t_token.secret
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.created_time
     *
     * @return the value of t_token.created_time
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.created_time
     *
     * @param createdTime the value for t_token.created_time
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.expires_time
     *
     * @return the value of t_token.expires_time
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public Date getExpiresTime() {
        return expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.expires_time
     *
     * @param expiresTime the value for t_token.expires_time
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setExpiresTime(Date expiresTime) {
        this.expiresTime = expiresTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.client_ip
     *
     * @return the value of t_token.client_ip
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.client_ip
     *
     * @param clientIp the value for t_token.client_ip
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.client_type
     *
     * @return the value of t_token.client_type
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.client_type
     *
     * @param clientType the value for t_token.client_type
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.e_code
     *
     * @return the value of t_token.e_code
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public String geteCode() {
        return eCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.e_code
     *
     * @param eCode the value for t_token.e_code
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void seteCode(String eCode) {
        this.eCode = eCode == null ? null : eCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_token.u_code
     *
     * @return the value of t_token.u_code
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public String getuCode() {
        return uCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_token.u_code
     *
     * @param uCode the value for t_token.u_code
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    public void setuCode(String uCode) {
        this.uCode = uCode == null ? null : uCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Token other = (Token) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAccessToken() == null ? other.getAccessToken() == null : this.getAccessToken().equals(other.getAccessToken()))
            && (this.getSecret() == null ? other.getSecret() == null : this.getSecret().equals(other.getSecret()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getExpiresTime() == null ? other.getExpiresTime() == null : this.getExpiresTime().equals(other.getExpiresTime()))
            && (this.getClientIp() == null ? other.getClientIp() == null : this.getClientIp().equals(other.getClientIp()))
            && (this.getClientType() == null ? other.getClientType() == null : this.getClientType().equals(other.getClientType()))
            && (this.geteCode() == null ? other.geteCode() == null : this.geteCode().equals(other.geteCode()))
            && (this.getuCode() == null ? other.getuCode() == null : this.getuCode().equals(other.getuCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_token
     *
     * @mbggenerated Fri Oct 27 17:14:48 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAccessToken() == null) ? 0 : getAccessToken().hashCode());
        result = prime * result + ((getSecret() == null) ? 0 : getSecret().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getExpiresTime() == null) ? 0 : getExpiresTime().hashCode());
        result = prime * result + ((getClientIp() == null) ? 0 : getClientIp().hashCode());
        result = prime * result + ((getClientType() == null) ? 0 : getClientType().hashCode());
        result = prime * result + ((geteCode() == null) ? 0 : geteCode().hashCode());
        result = prime * result + ((getuCode() == null) ? 0 : getuCode().hashCode());
        return result;
    }
}