package com.dbapp.mybatis.pojo;

import java.io.Serializable;
import java.util.Date;
import org.apache.ibatis.type.Alias;

/**
 * 实体类 - 表：t_uplog
 * @since 2017-10-10 10:02:21
 */
@Alias("Uplog")
public class Uplog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.id
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.pro_name
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.serial_number
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private String serialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.status
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.cur_version
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private String curVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.last_version
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private String lastVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.begin_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.end_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uplog.create_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_uplog
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.id
     *
     * @return the value of t_uplog.id
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.id
     *
     * @param id the value for t_uplog.id
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.pro_name
     *
     * @return the value of t_uplog.pro_name
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.pro_name
     *
     * @param proName the value for t_uplog.pro_name
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.serial_number
     *
     * @return the value of t_uplog.serial_number
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.serial_number
     *
     * @param serialNumber the value for t_uplog.serial_number
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber == null ? null : serialNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.status
     *
     * @return the value of t_uplog.status
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.status
     *
     * @param status the value for t_uplog.status
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.cur_version
     *
     * @return the value of t_uplog.cur_version
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public String getCurVersion() {
        return curVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.cur_version
     *
     * @param curVersion the value for t_uplog.cur_version
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setCurVersion(String curVersion) {
        this.curVersion = curVersion == null ? null : curVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.last_version
     *
     * @return the value of t_uplog.last_version
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public String getLastVersion() {
        return lastVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.last_version
     *
     * @param lastVersion the value for t_uplog.last_version
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setLastVersion(String lastVersion) {
        this.lastVersion = lastVersion == null ? null : lastVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.begin_time
     *
     * @return the value of t_uplog.begin_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.begin_time
     *
     * @param beginTime the value for t_uplog.begin_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.end_time
     *
     * @return the value of t_uplog.end_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.end_time
     *
     * @param endTime the value for t_uplog.end_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uplog.create_time
     *
     * @return the value of t_uplog.create_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uplog.create_time
     *
     * @param createTime the value for t_uplog.create_time
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uplog
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Uplog other = (Uplog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProName() == null ? other.getProName() == null : this.getProName().equals(other.getProName()))
            && (this.getSerialNumber() == null ? other.getSerialNumber() == null : this.getSerialNumber().equals(other.getSerialNumber()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCurVersion() == null ? other.getCurVersion() == null : this.getCurVersion().equals(other.getCurVersion()))
            && (this.getLastVersion() == null ? other.getLastVersion() == null : this.getLastVersion().equals(other.getLastVersion()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uplog
     *
     * @mbggenerated Tue Oct 10 10:02:21 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProName() == null) ? 0 : getProName().hashCode());
        result = prime * result + ((getSerialNumber() == null) ? 0 : getSerialNumber().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCurVersion() == null) ? 0 : getCurVersion().hashCode());
        result = prime * result + ((getLastVersion() == null) ? 0 : getLastVersion().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}